package hibernate;
// Generated 30 Jan, 2025 7:40:58 PM by Hibernate Tools 4.3.1



/**
 * Guestbook generated by hbm2java
 */
import javax.persistence.*;
@Entity
@Table(name="GuestBook")





public class Guestbook  implements java.io.Serializable {
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)

     private int vno;
     private String vname;
     private String msg;
     private String mdate;

    public Guestbook() {
    }

	
    public Guestbook(int vno) {
        this.vno = vno;
    }
    public Guestbook(int vno, String vname, String msg, String mdate) {
       this.vno = vno;
       this.vname = vname;
       this.msg = msg;
       this.mdate = mdate;
    }
   
    public int getVno() {
        return this.vno;
    }
    
    public void setVno(int vno) {
        this.vno = vno;
    }
    public String getVname() {
        return this.vname;
    }
    
    public void setVname(String vname) {
        this.vname = vname;
    }
    public String getMsg() {
        return this.msg;
    }
    
    public void setMsg(String msg) {
        this.msg = msg;
    }
    public String getMdate() {
        return this.mdate;
    }
    
    public void setMdate(String mdate) {
        this.mdate = mdate;
    }




}


